accounts/urls.py
from django.urls import path
from .views import (
    RegistUserView, HomeView, UserLoginView,
    UserLogoutView, UserView
)

app_name = 'accounts'
urlpatterns = [
    path('home/', HomeView.as_view(), name='home'),
    path('regist/', RegistUserView.as_view(), name='regist'),
    path('user_login/', UserLoginView.as_view(), name='user_login'),
    path('user_logout/', UserLogoutView.as_view(), name='user_logout'),
    path('user/', UserView.as_view(), name='user'),
]

psychology_project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from accounts.views import HomeView
from django.contrib.staticfiles.urls import static


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('psychology_tests/quizzes/', include(('psychology_tests.urls', 'psychology_tests'), namespace='psychology_tests')),
    path('psychology_tests/', include('psychology_tests.urls')),
    # path('quizzes/', include('quizzes.urls')),
    # path('psychology_tests/', include('psychology_tests.urls', namespace='psychology_tests'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

psychology_tests/urls.py
from django.urls import path
from .views import (QuizDetailView, QuizListView, 
                send_share_email,my_page, delete_result,
                delete_all_results, view_usage_log)
                


app_name = 'psychology_tests'

urlpatterns = [
    path('quiz_list/', QuizListView.as_view(), name='quiz_list'),
    path('quiz/detail/<int:pk>/', QuizDetailView.as_view(), name='quiz_detail'),
    path('send_email/', send_share_email, name='send_share_email'),
    path('my_page/', my_page, name='my_page'),
    path('delete_result/<int:result_id>/', delete_result, name='delete_result'),
    path('delete_all_results/', delete_all_results, name='delete_all_results'),
    path('view_usage_log/', view_usage_log, name='view_usage_log'),
]

psychology_tests/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone
import json

User = get_user_model()
"""カテゴリー"""
class ProductTypes(models.Model):
    name = models.CharField(max_length=1000)
    
    class Meta:
        db_table = 'product_types'
    
    def __str__(self):
        return self.name
    
    

"""問題"""
class Quiz(models.Model):
    title = models.CharField(max_length=1000)
    product_type = models.ForeignKey(
        ProductTypes, on_delete=models.CASCADE
    )
    detail = models.TextField()
    template_name = models.CharField(max_length=100, default='default_quiz_template.html')  # デフォルトテンプレート名

    
    class Meta:
        db_table = 'quiz'
        
    def __str__(self):
        return self.title

    
"""写真"""
class ProductPictures(models.Model):
    picture = models.FileField(upload_to='product_pictures/')
    product = models.ForeignKey(
        Quiz, on_delete=models.CASCADE
    )
    order = models.CharField(max_length=50, blank=True, null=True) 

    class Meta:
        db_table = 'product_pictures'
        ordering = ['order'] 
        
    def __str__(self):
        return f'{self.product.title}: {self.order}'
        

"""結果"""
class TestResult(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    date_taken = models.DateTimeField(auto_now_add=True)
    result_data = models.JSONField(default=dict)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'test_results'

    def __str__(self):
        return f"{self.user.username} - {self.quiz.title}"

psychology_tests/forms.py
from django import forms

class EmailForm(forms.Form):
    email = forms.EmailField(label='受信者のメールアドレス')
    message = forms.CharField(widget=forms.Textarea, label='メッセージ')

# from django.contrib.auth.forms import AuthenticationForm

# class EmailForm(AuthenticationForm):
#     username = forms.EmailField(label='メールアドレス')
#     password = forms.CharField(label='パスワード', widget=forms.PasswordInput())
#     remember = forms.BooleanField(label='ログイン状態を保持する', required=False)

psychology_tests/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView
from django.views.decorators.http import require_POST,  require_http_methods
from django.contrib.auth.mixins import LoginRequiredMixin
from . models import Quiz, TestResult, ProductPictures
from django.core.mail import send_mail
from django.core.validators import validate_email
from django.core.exceptions import ValidationError
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
import logging
from django.utils import timezone
from django.db.models import Count
from django.db.models.functions import ExtractHour
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.views.decorators.http import require_http_methods
from .forms import EmailForm  
from django.conf import settings


logger = logging.getLogger('usage')




class QuizDetailView(LoginRequiredMixin, DetailView):
    model = Quiz

    def get_template_names(self):
        if self.object.template_name:
            return [self.object.template_name]
        else:
            return ['psychology_tests/default_quiz_template.html']
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # 関連する画像を取得
        context['pictures'] = ProductPictures.objects.filter(product=self.object).order_by('order')
        return context
        
    def get(self, request, *args, **kwargs):
        self.object = self.get_object()  # オブジェクトを取得
        if request.user.is_authenticated:
            result_data = {"sample_key": "sample_value"}
            result = TestResult.objects.create(user=request.user, quiz=self.object)
            # print("TestResult created:", result)  # デバッグ情報を出力
            
            # ログ記録
            logger.debug(f'Quiz accessed: {self.object.title}, Category: {self.object.product_type.name}, Time: {timezone.now()}')
        else:
            # print("User is not authenticated")  # ユーザー認証がされていない場合のデバッグ
            logger.debug(f'Unauthorized access attempt to quiz: {self.object.title} at {timezone.now()}')
        return super().get(request, *args, **kwargs)        

    # def get(self, request, *args, **kwargs):
    #     self.object = self.get_object()
    #     if request.user.is_authenticated:
    #         logger.debug(f'Quiz accessed: {self.object.title}, Category: {self.object.product_type.name}, Time: {timezone.now()}')
    #     else:
    #         logger.debug(f'Unauthorized access attempt to quiz: {self.object.title} at {timezone.now()}')
    #     return super().get(request, *args, **kwargs)



@staff_member_required
def view_usage_log(request):
    # カテゴリ別の集計
    category_usage = TestResult.objects.values('quiz__product_type__name').annotate(total=Count('id')).order_by('-total')
    
    # 時間帯別の集計
    hour_usage = TestResult.objects.annotate(hour=ExtractHour('created_at')).values('hour').annotate(total=Count('id')).order_by('hour')
    
    return render(request, "psychology_tests/view_usage_log.html", {
        'category_usage': category_usage,
        'hour_usage': hour_usage
    })

    
# @staff_member_required
# def view_usage_log(request):
#     log_content = "Log file not found."
#     try:
#         with open('usage.log', 'r') as file:
#             log_content = file.read()
#     except IOError:
#         pass
#     return render(request, "psychology_tests/view_usage_log.html", {'log_content': log_content})


class QuizListView(LoginRequiredMixin, ListView):
    model = Quiz
    template_name = 'psychology_tests/quiz_list.html'
    
    def get_queryset(self):
        queryset = super().get_queryset()
        product_type_name = self.request.GET.get('product_type_name', '')
        if product_type_name:
            queryset = queryset.filter(product_type__name__icontains=product_type_name)
        return queryset
    
    # def get(self, request, *args, **kwargs):
    #     quiz = self.get_object()
    #     TestResult.objects.create(user=request.user, quiz=quiz)
    #     return super().get(request, *args, **kwargs)
    

# こっちがよしこ？
# @require_http_methods(["POST"])
# def send_share_email(request):
#     if request.method == 'POST':
#         recipient_email = request.POST.get('email')
#         quiz_id = request.POST.get('quiz_id')  # ユーザー指定
#         subject = '心理テストが共有されました！'
#         sender_email = 'your-email@gmail.com'  
#         page_url = reverse('psychology_tests:quiz_detail', kwargs={'pk': quiz_id})
#         full_page_url = request.build_absolute_uri(page_url)

#         message = f"以下のリンクから心理テストを確認できます。アカウント登録がまだの方は新規ユーザー登録をお願いします！: {full_page_url}"

#         send_mail(subject, message, sender_email, [recipient_email])

#         # リンクを含むメッセージを返す
#         return HttpResponse(f"メールが送信されました！<br><br>"
#                             f"<a href='{settings.LINK_URL_1}'>心理テスト一覧に戻る</a>")
#     else:
#         return HttpResponse("アドレスを間違えています。")

@require_http_methods(["POST"])
def send_share_email(request):
    if request.method == 'POST':
        recipient_email = request.POST.get('email')
        quiz_id = request.POST.get('quiz_id')  # ユーザー指定
        
        try:
            validate_email(recipient_email)
        except ValidationError:
            error_message = "入力されたアドレスが間違っています、送信先を確認してください😟！"
            return HttpResponse(f"{error_message}<br><br>"
                                f"<a href='{settings.LINK_URL_1}'>心理テスト一覧に戻る</a>")

        subject = '心理テストが共有されました☺'
        page_url = reverse('psychology_tests:quiz_detail', kwargs={'pk': quiz_id})
        full_page_url = request.build_absolute_uri(page_url)

        message = f"以下のリンクから心理テストを確認できます。アカウント登録がまだの方は新規ユーザー登録をお願いします🤗: {full_page_url}"

        # 送信者のメールアドレスを指定しないSMTPしてるから！
        send_mail(subject, message, None, [recipient_email])

        # メール送信成功
        success_message = "メールが送信されました😺！"
        return HttpResponse(f"{success_message}<br><br>"
                            f"<a href='{settings.LINK_URL_1}'>心理テスト一覧に戻る</a>")

@login_required
def my_page(request):
    test_results = TestResult.objects.filter(user=request.user)
    return render(request, 'user.html', {'test_results': test_results})

@login_required
@require_POST
def delete_result(request, result_id):
    result = get_object_or_404(TestResult, id=result_id, user=request.user)  # ユーザーが所有する個別履歴のみ削除
    result.delete()
    return HttpResponse(f"削除しました！<br><br>"
                        f"<a href='{settings.LINK_URL_2}'>マイページに戻る</a>")  # リダイレクトするページ
    # return HttpResponse("""
    #     削除しました！<br><br>
    #     <a href="http://127.0.0.1:8000/accounts/user/">マイページに戻る</a>
    # """)  # 削除後にリダイレクトするページ

@login_required
@require_POST
def delete_all_results(request):
    # ユーザーの全履歴を削除
    TestResult.objects.filter(user=request.user).delete()
    # 削除後のメッセージを表示、リダイレクト
    return HttpResponse(f"削除しました！<br><br>"
                        f"<a href='{settings.LINK_URL_2}'>マイページに戻る</a>")  # 削除後にリダイレクトするページ
    # return HttpResponse("""
    #     全ての履歴を削除しました！<br><br>
    #     <a href="http://127.0.0.1:8000/accounts/user/">マイページに戻る</a>
    # """)

templates/psychology_tests/quiz_list.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/list.css' %}?v=1.5" type="text/css">
{% endblock %}

{% block title %}心理テスト一覧{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2>心理テスト一覧</h2><br>
    <form method="get" action="{% url 'psychology_tests:quiz_list' %}" class="search-form search-form-short">
        <div class="input-group mb-3 custom-input-group">
            <input type="text" class="form-control smaller-input" name="product_type_name" placeholder="カテゴリーを入力" value="{{ product_type_name }}" aria-label="Recipient's username" aria-describedby="button-addon2">
            <button class="btn btn-primary smaller-button" type="submit" id="button-addon2">検索する</button>
        </div>
    </form>
    <table class="table table-striped table-bordered text-center">
        <thead>
            <tr>
                <th>カテゴリー</th>
                <th>テスト</th>
            </tr>
        </thead>
        <tbody>
            {% for quiz in object_list %}
            <tr>
                <td class="category-social-life">{{ quiz.product_type.name }}</td>
                <td><a href="{% url 'psychology_tests:quiz_detail' quiz.pk %}">{{ quiz.title }}</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

templates/psychology_tests/test1.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/test.css' %}?v=1.5" type="text/css">
{% endblock %}

{% block title %}{{ quiz.title }}{% endblock %}

{% block content %}
<div class="quiz-container">
    <h1>{{ quiz.title }}</h1>
    <div class="quiz-images">
        {% for picture in pictures %}
        <img src="{{ picture.picture.url }}" alt="Product Image {{ forloop.counter }}" class="product-image uniform-size">
        {% endfor %}
    </div>
    <p class="question label">目の前に一瞬で地球を爆発できる危険なスイッチがあります。どんなデザインですか？直感で１つ選んでください😊</p>
    <div class="choices label">
        <ol>
            <li>赤色の丸形の押しボタン</li>
            <li>青色の四角形の押しボタン</li>
            <li>縦に３つ並んでいるカラフルなスイッチ</li>
            <li>四角い真っ黒なスイッチ</li>
        </ol>
    </div>
    <div class="results label">
        <p>▼診断結果▼</p> 
        <ol><br>
            <li>サイコパス傾向はほとんどありません。通常の健全な思考回路を持っている証拠です。</li>
            <li>サイコパスレベルがかなり高いです。あなたは良心が欠如してる可能性が高いです。</li>
            <li>サイコパスの気質があるかもしれません。ときどき周囲の人たちが引いてしまうような言動や行動を取ってしまうことがあるようです。</li>
            <li>少しサイコパス的な特徴があるようですが、安心してください。基本的には一般的な人と同じような感性を持っています。</li>
        </ol><br>
        <p>結果はいかがでしたか？</p>
        <p>この内容を共有したい時は送信先を入力してね😘</p>
        <p>info.psycho2024@gmail.comからメールが届きます🫰</p>
    </div>
    <form action="{% url 'psychology_tests:send_share_email' %}" method="post" class="share-form">
        {% csrf_token %}
        <input type="hidden" name="quiz_id" value="{{ quiz.id }}">
        <div class="email-container custom-email-form label">
        <label for="email">メールアドレス:</label>
        <input type="email" id="email" name="email" required style="width: 50%;">
        <button type="submit" class="button" onclick="return confirm('送信しますか?');">送信</button>
        </div>
    </form>
    </div>
{% endblock %}

templates/psychology_tests/test2.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/test.css' %}?v=1.5" type="text/css">
{% endblock %}

{% block title %}{{ quiz.title }}{% endblock %}

{% block content %}
<div class="quiz-container">
    <h1>{{ quiz.title }}</h1>
    <div class="quiz-images">
        {% for picture in pictures %}
        <img src="{{ picture.picture.url }}" alt="Product Image {{ forloop.counter }}" class="product-image uniform-size">
        {% endfor %}
    </div>
    <p class="question label">空に向かって４種類の乗り物があります。あなたはどれに乗りますか？直感で１つ選んでください😊</p>
    <div class="choices label">
        <ol>
            <li>赤色の気球</li>
            <li>飛行機</li>
            <li>ロケット</li>
            <li>空を飛べる羽丸形の押しボタン</li>
        </ol>
    </div>
    <div class="results label">
        <p>▼診断結果▼</p> 
        <ol>
            <li>あなたは平和を好む人。そして相手の性格をじっくり観察できるタイプだから、人間関係におけるトラブルはほとんどないでしょう。</li>
            <li>あなたは物事を合理的に考える人。人に左右さることや直感で「何か」を選択をすることはありませんので、周りからの信頼は厚いでしょう。</li>
            <li>あなたは秘密主義なタイプ。他人との距離感を大切にする人なので、誤解されてしまうことも多いですが、そのミステリアスな感じに惹かれる人は多いでしょう。</li>
            <li>あなたはユーモアセンスが溢れるタイプ。あなたの考え、あなたの言葉を大切に、そのままのあなたでいてください。</li>
        </ol><br>
        <p>結果はいかがでしたか？</p>
        <p>この内容を共有したい時は送信先を入力してね😘</p>
        <p>info.psycho2024@gmail.comからメールが届きます🫰</p>
    </div>
    <form action="{% url 'psychology_tests:send_share_email' %}" method="post" class="share-form">
        {% csrf_token %}
        <input type="hidden" name="quiz_id" value="{{ quiz.id }}">
        <div class="email-container custom-email-form label">
        <label for="email">メールアドレス:</label>
        <input type="email" id="email" name="email" required style="width: 50%;">
        <button type="submit" class="button" onclick="return confirm('送信しますか?');">送信</button>
        </div>
    </form>
    </div>
{% endblock %}

templates/psychology_tests/test3.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/test.css' %}?v=1.5" type="text/css">
{% endblock %}

{% block title %}{{ quiz.title }}{% endblock %}

{% block content %}
<div class="quiz-container">
    <h1>{{ quiz.title }}</h1>
    <div class="quiz-images">
        {% for picture in pictures %}
        <img src="{{ picture.picture.url }}" alt="Product Image {{ forloop.counter }}" class="product-image uniform-size">
        {% endfor %}
    </div>
    <p class="question label">人によって見え方が違うイラストがあります。どんなイラストが書いてあるか直感で１つ選んでください😊</p>
    <div class="choices label">
        <ol>
            <li>おじさんの顔</li>
            <li>ウサギの顔</li>
            <li>電車やバス</li>
            <li>がま口のポーチ</li>
        </ol>
    </div>
    <div class="results label">
        <p>▼診断結果▼</p> 
        <ol>
            <li>あなたは友達から、同じ目線で何でも気軽に話せると慕われているタイプ。一緒にいると「居心地が良い」と思われているようです。</li>
            <li>あなたは、ちょっぴり天然で何を言い出すか判らないところがあるみたい。一緒に居て楽しい、面白い、ワクワクする…と思われていそうです。</li>
            <li>あなたは友達から、とても知的で頼りになると思われているようです。本当に悩みを抱えてしまった時や、難しい問題に直面した時など、あなたにまず意見を聞きたいと思う人が多いのではないでしょうか？</li>
            <li>あなたは友達から、客観的にこの世界のことを良く観察し、熟知も理解もしている賢者だと思われていそうです。</li>
        </ol><br>
        <p>結果はいかがでしたか？</p>
        <p>この内容を共有したい時は送信先を入力してね😘</p>
        <p>info.psycho2024@gmail.comからメールが届きます🫰</p>
    </div>
    <form action="{% url 'psychology_tests:send_share_email' %}" method="post" class="share-form">
        {% csrf_token %}
        <input type="hidden" name="quiz_id" value="{{ quiz.id }}">
        <div class="email-container custom-email-form label">
        <label for="email">メールアドレス:</label>
        <input type="email" id="email" name="email" required style="width: 50%;">
        <button type="submit" class="button" onclick="return confirm('送信しますか?');">送信</button>
        </div>
    </form>
    </div>
{% endblock %}

templates/psychology_tests/test4.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/test.css' %}?v=1.5" type="text/css">
{% endblock %}

{% block title %}{{ quiz.title }}{% endblock %}

{% block content %}
<div class="quiz-container">
    <h1>{{ quiz.title }}</h1>
    <div class="quiz-images">
        {% for picture in pictures %}
        <img src="{{ picture.picture.url }}" alt="Product Image {{ forloop.counter }}" class="product-image uniform-size">
        {% endfor %}
    </div>
    <p class="question label">あなたはどんなポーズで寝ますか？この問題はあなたの性格を診断します。直感で１つ選んでください😊</p>
    <div class="choices label">
        <ol>
            <li>うつぶせ</li>
            <li>お腹に丸まって</li>
            <li>横向き</li>
            <li>あおむけ</li>
        </ol>
    </div>
    <div class="results label">
        <p>▼診断結果▼</p> 
        <ol>
            <li>もし隣に誰かいるのなら、一人で独占したいタイプ</li>
            <li>誰かに守られたいあなたは寂しがり屋なタイプ</li>
            <li>あなたは人に安心感を与えられる器用なタイプ</li>
            <li>あなたはオープンで柔軟なタイプ</li>
        </ol><br>
        <p>結果はいかがでしたか？</p>
        <p>この内容を共有したい時は送信先を入力してね😘</p>
        <p>info.psycho2024@gmail.comからメールが届きます🫰</p>
    </div>
    <form action="{% url 'psychology_tests:send_share_email' %}" method="post" class="share-form">
        {% csrf_token %}
        <input type="hidden" name="quiz_id" value="{{ quiz.id }}">
        <div class="email-container custom-email-form label">
        <label for="email">メールアドレス:</label>
        <input type="email" id="email" name="email" required style="width: 50%;">
        <button type="submit" class="button" onclick="return confirm('送信しますか?');">送信</button>
        </div>
    </form>
    </div>
{% endblock %}

templates/psychology_tests/test5.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/test.css' %}?v=1.5" type="text/css">
{% endblock %}

{% block title %}{{ quiz.title }}{% endblock %}

{% block content %}
<div class="quiz-container">
    <h1>{{ quiz.title }}</h1>
    <div class="quiz-images">
        {% for picture in pictures %}
        <img src="{{ picture.picture.url }}" alt="Product Image {{ forloop.counter }}" class="product-image uniform-size">
        {% endfor %}
    </div>
    <p class="question label">久しぶりに、気合いを入れて家の掃除をしようとしているあなた。さて、次のうちどこから手をつけますか？直感で１つ選んでください😊</p>
    <div class="choices label">
        <ol>
            <li>玄関</li>
            <li>寝室</li>
            <li>リビング</li>
            <li>水回り</li>
        </ol>
    </div>
    <div class="results label">
        <p>▼診断結果▼</p> 
        <ol>
            <li>いくら恋人だとしても、「誰とどこに行くの？」なんて束縛や嫉妬が激しい相手はNG！それぞれの時間を好きに過ごせるような、自由な恋愛がベストだと思っています。</li>
            <li>一緒にいて心が癒されるような、安心できる人を恋人にしたいと思っているでしょう。刺激的な恋愛よりも、落ち着いた恋愛を好むタイプです。</li>
            <li>深層心理では、リビングは心そのものです。『心に余裕があってこその恋愛』と考えるタイプなので、仕事・人間関係がうまくいっているときに恋愛を楽しみたいと思っています。</li>
            <li>清廉潔白な関係が理想なので、嘘をついたりごまかしたりするような相手は敬遠したくなるでしょう。心だけでなく、見た目の美しさも恋愛において重要だと思っているタイプです。</li>
        </ol><br>
        <p>結果はいかがでしたか？</p>
        <p>この内容を共有したい時は送信先を入力してね😘</p>
        <p>info.psycho2024@gmail.comからメールが届きます🫰</p>
    </div>
    <form action="{% url 'psychology_tests:send_share_email' %}" method="post" class="share-form">
        {% csrf_token %}
        <input type="hidden" name="quiz_id" value="{{ quiz.id }}">
        <div class="email-container custom-email-form label">
        <label for="email">メールアドレス:</label>
        <input type="email" id="email" name="email" required style="width: 50%;">
        <button type="submit" class="button" onclick="return confirm('送信しますか?');">送信</button>
        </div>
    </form>
    </div>
{% endblock %}

templates/psychology_tests/test6.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/test.css' %}?v=1.5" type="text/css">
{% endblock %}

{% block title %}{{ quiz.title }}{% endblock %}

{% block content %}
<div class="quiz-container">
    <h1>{{ quiz.title }}</h1>
    <div class="quiz-images">
        {% for picture in pictures %}
        <img src="{{ picture.picture.url }}" alt="Product Image {{ forloop.counter }}" class="product-image uniform-size">
        {% endfor %}
    </div>
    <p class="question label">森の中で迷ってしまったあなた。歩き続けていくと『お菓子の家』が見えてきました。しかし、鍵がかかっていて中へ入れません。次のうちどこを壊して中に入りますか？直感で１つ選んでください😊</p>
    <div class="choices label">
        <ol>
            <li>窓</li>
            <li>玄関</li>
            <li>勝手口</li>
            <li>天窓</li>
        </ol>
    </div>
    <div class="results label">
        <p>▼診断結果▼</p> 
        <ol>
            <li>人間関係におけるバランス力が抜群なタイプです。気配り上手で、相手のリアクションを見ながら臨機応変に対応を変えていくことができます。さまざまな人が集まるコミュニティの中でも、抜群のバランス力でうまく立ち回ることができるタイプです。</li>
            <li>人間関係のバランス力がやや低いタイプ。相手が誰であっても思ったことをストレートに口に出すので、人と衝突することも多いかもしれません。その反面、そんなあなたの熱い気持ちをわかってくれる人と出会うことができれば、最強のリーダーになれる可能性も秘めています。</li>
            <li>人間関係のバランス力が高いタイプです。人を傷つけないやさしさがあるので、気の合う少数の友人とうまく人間関係を築くことができます。自分から積極的に人と関わるようにすると、人生がさらに豊かになるかもしれません。</li>
            <li>人間関係におけるバランス力が皆無です。そもそも人と深く関わることを望んでいないので、『一匹狼タイプ』といえます。カリスマ性は高いですが、「本当に心を許せる人がいない…」と心の中では孤独を抱えているかもしれません。</li>
        </ol><br>
        <p>結果はいかがでしたか？</p>
        <p>この内容を共有したい時は送信先を入力してね😘</p>
        <p>info.psycho2024@gmail.comからメールが届きます🫰</p>
    </div>
    <form action="{% url 'psychology_tests:send_share_email' %}" method="post" class="share-form">
        {% csrf_token %}
        <input type="hidden" name="quiz_id" value="{{ quiz.id }}">
        <div class="email-container custom-email-form label">
        <label for="email">メールアドレス:</label>
        <input type="email" id="email" name="email" required style="width: 50%;">
        <button type="submit" class="button" onclick="return confirm('送信しますか?');">送信</button>
        </div>
    </form>
    </div>
{% endblock %}