accounts/urls.py
from django.urls import path
from .views import (
    RegistUserView, HomeView, UserLoginView,
    UserLogoutView, UserView
)

app_name = 'accounts'
urlpatterns = [
    path('home/', HomeView.as_view(), name='home'),
    path('regist/', RegistUserView.as_view(), name='regist'),
    path('user_login/', UserLoginView.as_view(), name='user_login'),
    path('user_logout/', UserLogoutView.as_view(), name='user_logout'),
    path('user/', UserView.as_view(), name='user'),
]

psychology_project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from accounts.views import HomeView
from django.contrib.staticfiles.urls import static


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('psychology_tests/quizzes/', include(('psychology_tests.urls', 'psychology_tests'), namespace='psychology_tests')),
    path('psychology_tests/', include('psychology_tests.urls')),
    # path('quizzes/', include('quizzes.urls')),
    # path('psychology_tests/', include('psychology_tests.urls', namespace='psychology_tests'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

psychology_tests/urls.py
from django.urls import path
from .views import (QuizDetailView, QuizListView, 
                send_share_email,my_page, delete_result,
                delete_all_results, view_usage_log)
                


app_name = 'psychology_tests'

urlpatterns = [
    path('quiz_list/', QuizListView.as_view(), name='quiz_list'),
    path('quiz/detail/<int:pk>/', QuizDetailView.as_view(), name='quiz_detail'),
    path('send_email/', send_share_email, name='send_share_email'),
    path('my_page/', my_page, name='my_page'),
    path('delete_result/<int:result_id>/', delete_result, name='delete_result'),
    path('delete_all_results/', delete_all_results, name='delete_all_results'),
    path('view_usage_log/', view_usage_log, name='view_usage_log'),
]

templates/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/test.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/mypage.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/list.css' %}" type="text/css">
    <title>{% block title %}ログイン{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light navbar-custom">
        <a class="navbar-brand navbar-brand-custom" href="{% url 'accounts:home' %}">★このアプリについて★</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:user_logout' %}">ログアウト</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'psychology_tests:quiz_list' %}">心理テスト一覧</a>
                </li>
                {% if user.is_staff %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'psychology_tests:view_usage_log' %}">ログの閲覧</a>
                </li>
                {% endif %}
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:user_login' %}">ログイン</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:regist' %}">新規ユーザー登録</a>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:user' %}">マイページ</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container h-100">
        <div class="row align-items-center justify-content-center h-100">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        {% block content %}
                        <!-- ここにログインフォームが表示される -->
                        {% endblock %}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/custom.css' %}">
{% endblock %}

<title>{% block title %}アプリについて{% endblock %}</title>

{% block content %}
<div class="content-text">
<h4>心理テストを楽しめます👯</h4><br>
<h6>まずはユーザー登録してね！</h6>
<h6>登録後はマイページにあなたの履歴が自動保存されます🌞</h6>
<h6>気になる題名をクリック、４つの選択肢を選ぶだけ♪</h6>
<h6>診断結果は指定のメールアドレスに送信可能👌</h6>
<h6>話題作りに活用してね🤗</h6>
    
{% endblock %}👯

templates/regist.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/custom.css' %}">
{% endblock %}

{% block title %}新規ユーザー登録{% endblock %}

{% block content %}
<div class="form-container">
    <form method="POST" action="{% url 'accounts:regist' %}"> 
    {% csrf_token %}
    {% for field in form %}
        <div class="form-group">
            {{ field.label_tag }}
            {{ field }}
            {% if field.errors %}
                {% for error in field.errors %}
                    <div class="error">{{ error }}</div>
                {% endfor %}
            {% endif %}
        </div>
    {% endfor %}
    <input type="submit" value="新規ユーザー登録" class="input-submit">
</form>
</div>
{% endblock %}

templates/user.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/mypage.css' %}?v=1.5" type="text/css">
{% endblock %}

{% block title %}マイページ{% endblock %}

{% block content %}
<div class="container">
    <h2>心理テスト履歴</h2>
    
    {% if test_results %}
        <p class="common-text-color">全ての履歴が表示されます。</p>
        <p class="common-text-color">詳細を見るにはタイトルをクリックしてください😉</p>
    
        <form action="{% url 'psychology_tests:delete_all_results' %}" method="post" style="text-align: center;">
            {% csrf_token %}
            <button type="submit" class="delete-all-button" onclick="return confirm('全ての履歴を削除しますか？');">
                全ての履歴を削除する
            </button>
        </form>

        <ul class="list-unstyled">
            {% for result in test_results %}
            <li class="mb-2">
                <div class="content-wrapper ">
                    <div class="title common-text-color">
                        <a href="{% url 'psychology_tests:quiz_detail' pk=result.quiz.id %}" class="text-decoration-none common-text-color">
                            ・{{ result.quiz.title }}
                        </a>
                        
                    </div>
                    <div class="details">
                        <span class="date common-text-color">{{ result.date_taken }}</span>
                        <form action="{% url 'psychology_tests:delete_result' result_id=result.id %}" method="post" class="delete-form">
                            {% csrf_token %}
                            <button type="submit" class="delete-button" onclick="return confirm('削除しますか?');">削除</button>
                        </form>
                    </div>
                </div>
            </li>
            {% endfor %}
        </ul>
    {% else %}
        <div class="text-muted text-center common-text-color">まだ履歴がありません😫</div>
        <div class="text-muted text-center common-text-color">心理テストを開始してください🤓</div>
    {% endif %}
</div>
{% endblock %}

templates/user_login.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/custom.css' %}">
{% endblock %}

{% block title %}ログイン{% endblock %}

{% block content %}
<div class="form-container">
    <form method="POST" action="{% url 'accounts:user_login' %}">
        {% csrf_token %}
        {% if form.non_field_errors %}
            <div class="error">
                {% for error in form.non_field_errors %}
                    {{ error }}
                {% endfor %}
            </div>
        {% endif %}
        {% for field in form %}
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field }}
            {% if field.errors %}
                {% for error in field.errors %}
                    <div class="error">{{ error }}</div>
                {% endfor %}
            {% endif %}
        </div>
        {% endfor %}
        <input type="hidden" name="next" value="{{ request.GET.next }}">
        <input type="submit" value="ログイン" class="input-submit">
    </form>
</div>
{% endblock %}